name: Build and Upload Pull Request
 
on: 
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, reopened ]

jobs:
  
  build-gui:
    runs-on: windows-latest
    env:
     ACTIONS_ALLOW_UNSECURE_COMMANDS: true
 
    steps:
    - uses: actions/checkout@v2.7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderWPF
    - name: Build Windows GUI
      run: dotnet publish TwitchDownloaderWPF -p:PublishProfile=Windows -p:DebugType=Portable
    
    - name: Download FFmpeg To Workspace
      # You may pin to the exact commit or the version.
      # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
      uses: carlosperate/download-file-action@v1.1.2
      with:
        # URL of the file to download
        file-url: https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
        # New filename to rename the downloaded file
        file-name: ffmpeg.zip
        
    - name: Bundle FFmpeg
      run: tar xfz ffmpeg.zip --strip-components=1; copy bin/ffmpeg.exe TwitchDownloaderWPF/bin/Release/net6.0-windows/publish/win-x64/ffmpeg.exe

    - name: Upload Windows GUI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderGUI-Windows-x64.zip
        path: TwitchDownloaderWPF/bin/Release/net6.0-windows/publish/win-x64

  build-cli:
    runs-on: ubuntu-20.04
    needs: [build-gui]
    steps:
    - uses: actions/checkout@v2.7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderCLI
    - name: Build Windows CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=Windows -p:DebugType=Portable
    - name: Build Linux CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=Linux -p:DebugType=Portable
    - name: Build LinuxAlpine CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=LinuxAlpine -p:DebugType=Portable
    - name: Build LinuxArm CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=LinuxArm -p:DebugType=Portable
    - name: Build LinuxArm64 CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=LinuxArm64 -p:DebugType=Portable

    - name: Upload Windows CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-Windows-x64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/Windows

    - name: Upload Linux CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-Linux-x64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/Linux

    - name: Upload LinuxAlpine CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-LinuxAlpine-x64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/LinuxAlpine

    - name: Upload LinuxArm CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-LinuxArm.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/LinuxArm
        
    - name: Upload LinuxArm64 CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-LinuxArm64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/LinuxArm64

  build-cli-mac:
    runs-on: macos-latest
    needs: [build-cli]
    steps:
    - uses: actions/checkout@v2.7.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore TwitchDownloaderCLI
    - name: Build MacOS CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=MacOS -p:DebugType=Portable
    - name: Build MacOSArm64 CLI
      run: dotnet publish TwitchDownloaderCLI -p:PublishProfile=MacOSArm64 -p:DebugType=Portable

    - name: Upload MacOS CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-MacOS-x64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/MacOS

    - name: Upload MacOSArm64 CLI Artifact Asset
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TwitchDownloaderCLI-MacOSArm64.zip
        path: TwitchDownloaderCLI/bin/Release/net6.0/publish/MacOSArm64
